version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-cymulate
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root123
      MONGO_INITDB_DATABASE: cymulate
    ports:
      - 27017:27017
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ${HOME}/mongodb-cymulate-data:/data/db
    networks:
      - mongo-network-cymulate
networks:
  mongo-network-cymulate:
    name: mongo-network-cymulate
